version: "2"

services:
  autoblockchainify:
    restart: unless-stopped
    image: zeitgitter/autoblockchainify
    # Enable the following lines to build from local tree while using
    # the current PyPi version of autoblockchainify. This is rarely used.
    # If you want to build fully from your local tree, use
    # `docker-compose-dev.yml` and `make docker-dev`.
    # Use e.g. `VERSIONMATCH===0.9.4 docker-compose build` to use a specific
    # version from PyPi (`${VERSIONMATCH}` is then `==0.9.4`).
    #build:
    #  context: ./autoblockchainify
    #  args:
    #    VERSIONMATCH: ${VERSIONMATCH}
    container_name: autoblockchainify
    env_file:
      - "server.env"
    volumes:
      - /wherever/your/data/is:/blockchain
